In [1]:
import os
import cv2 
import numpy as np
from os.path import join
import pandas as pd

In [2]:
def automatic_brightness_and_contrast(image, clip_hist_percent=1):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Calculate grayscale histogram
    hist = cv2.calcHist([gray],[0],None,[256],[0,256])
    hist_size = len(hist)

    # Calculate cumulative distribution from the histogram
    accumulator = []
    accumulator.append(float(hist[0]))
    for index in range(1, hist_size):
        accumulator.append(accumulator[index -1] + float(hist[index]))
    maximum = accumulator[-1]
    clip_hist_percent *= (maximum/100.0)
    clip_hist_percent /= 2.0

    # Locate left cut
    minimum_gray = 0
    while accumulator[minimum_gray] < clip_hist_percent:
        minimum_gray += 1

    # Locate right cut
    maximum_gray = hist_size -1
    while accumulator[maximum_gray] >= (maximum - clip_hist_percent):
        maximum_gray -= 1

    # Calculate alpha and beta values
    alpha = 255 / (maximum_gray - minimum_gray)
    beta = -minimum_gray * alpha
    auto_result = cv2.convertScaleAbs(image, alpha=alpha, beta=beta)
    return (auto_result, alpha, beta)




In [3]:

cwd=os.getcwd()
print(cwd)
cwd=os.path.join(cwd,'DATASET')
os.chdir('male')
i=0
print(cwd)
for(dirname, dirs, files) in os.walk('.'):
    for filename in files:
        if filename.endswith('.jpg') :
            #im=cv2.imread(os.path.join(dirname,filename))
            #cv2.imwrite(cwd+'\extra '+filename,im) 
            print('ignore')
        if filename.endswith('.png') :
            i=i+1
            
            image = cv2.imread(os.path.join(dirname,filename))
            """
            g0=cv2.pyrDown(image)
            g1=cv2.pyrDown(g0)
            g2=cv2.pyrDown(g1)
            g3=cv2.pyrDown(g2)
            g4=cv2.pyrDown(g3)
            h3=cv2.pyrUp(g4)
            h2=cv2.pyrUp(h3)
            h1=cv2.pyrUp(h2)
            h0=cv2.pyrUp(h1)
            originallvl=cv2.pyrUp(h0)

            x,y,z=originallvl.shape
            image=cv2.resize(image,(y,x))

            g0=cv2.pyrDown(image)
            g1=cv2.pyrDown(g0)
            g2=cv2.pyrDown(g1)
            g3=cv2.pyrDown(g2)
            g4=cv2.pyrDown(g3)
            h3=cv2.pyrUp(g4)
            h2=cv2.pyrUp(h3)
            h1=cv2.pyrUp(h2)
            h0=cv2.pyrUp(h1)
            l0=cv2.subtract(g0,h0)
            
        

            lr0=cv2.resize(l0,(y,x))
            
            norm0=cv2.normalize(lr0,None,0,255,cv2.NORM_MINMAX)
            rn0=cv2.add(image,lr0)
            
            new_image = cv2.convertScaleAbs(rn0, alpha=1, beta=5)
            lookUpTable = np.empty((1,256), np.uint8)
            for j in range(256):
                lookUpTable[0,j] = np.clip(pow(j / 255.0, 1.5) * 255.0, 0, 255)
                res = cv2.LUT(new_image, lookUpTable)
           # res=cv2.resize(res,(560,385))
            #image=cv2.resize(image,(560,385))
            w=filename.split('.')
            filename=w[0]+".jpg"
            """
            
            
            name=dirname.split('\\')
                               
            name1=cwd+"\img"+str(i)+" "+name[-1]+" "+filename
            print(name1)
            
            cv2.imwrite(name1,image)
                
            print(i)
        
        
            

            

E:\COM\PROJECT
E:\COM\PROJECT\DATASET
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ign

E:\COM\PROJECT\DATASET\img105 left-bot 20591998,-7,-F.png
105
E:\COM\PROJECT\DATASET\img106 left-bot 27973052,-7,-F.png
106
E:\COM\PROJECT\DATASET\img107 left-bot 28703247,-7,-F.png
107
E:\COM\PROJECT\DATASET\img108 left-bot 30386830,-7,-F.png
108
E:\COM\PROJECT\DATASET\img109 left-bot 32090010,-7,-F.png
109
E:\COM\PROJECT\DATASET\img110 left-bot 34099727,-7,-F.png
110
E:\COM\PROJECT\DATASET\img111 left-bot 37909546,-7,-F.png
111
E:\COM\PROJECT\DATASET\img112 left-bot 38326663,-7,-F.png
112
E:\COM\PROJECT\DATASET\img113 left-bot 38741145,-7,-F.png
113
E:\COM\PROJECT\DATASET\img114 left-bot 39038749,-7,-F.png
114
E:\COM\PROJECT\DATASET\img115 left-top 20591998,-7,-F.png
115
E:\COM\PROJECT\DATASET\img116 left-top 27973052,-7,-F.png
116
E:\COM\PROJECT\DATASET\img117 left-top 28703247,-7,-F.png
117
E:\COM\PROJECT\DATASET\img118 left-top 30386830,-7,-F.png
118
E:\COM\PROJECT\DATASET\img119 left-top 32090010,-7,-F.png
119
E:\COM\PROJECT\DATASET\img120 left-top 34099727,-7,-F.png
120
E:\COM\P

232
E:\COM\PROJECT\DATASET\img233 left-bot 39591048,-10,-F.png
233
E:\COM\PROJECT\DATASET\img234 left-bot 39733277,-10,-F.png
234
E:\COM\PROJECT\DATASET\img235 left-top 05950529,-10,-F.png
235
E:\COM\PROJECT\DATASET\img236 left-top 12312590,-10,-F.png
236
E:\COM\PROJECT\DATASET\img237 left-top 19997651,-10,-F.png
237
E:\COM\PROJECT\DATASET\img238 left-top 20276633,-10,-F.png
238
E:\COM\PROJECT\DATASET\img239 left-top 20501885,-10,-F.png
239
E:\COM\PROJECT\DATASET\img240 left-top 20847453,-10,-F.png
240
E:\COM\PROJECT\DATASET\img241 left-top 24992379,-10,-F.png
241
E:\COM\PROJECT\DATASET\img242 left-top 36592932,-10,-F.png
242
E:\COM\PROJECT\DATASET\img243 left-top 39591048,-10,-F.png
243
E:\COM\PROJECT\DATASET\img244 left-top 39733277,-10,-F.png
244
E:\COM\PROJECT\DATASET\img245 right-bot 05950529,-10,-F.png
245
E:\COM\PROJECT\DATASET\img246 right-bot 12312590,-10,-F.png
246
E:\COM\PROJECT\DATASET\img247 right-bot 19997651,-10,-F.png
247
E:\COM\PROJECT\DATASET\img248 right-bot 20276633

359
E:\COM\PROJECT\DATASET\img360 left-top 38268204,-14,-F.png
360
E:\COM\PROJECT\DATASET\img361 right-bot 08089699,-14,-F.png
361
E:\COM\PROJECT\DATASET\img362 right-bot 12966537,-14,-F.png
362
E:\COM\PROJECT\DATASET\img363 right-bot 26343359,-14,-F.png
363
E:\COM\PROJECT\DATASET\img364 right-bot 26475250,-14,-F.png
364
E:\COM\PROJECT\DATASET\img365 right-bot 26784158,-14,-F.png
365
E:\COM\PROJECT\DATASET\img366 right-bot 27160245,-14,-F.png
366
E:\COM\PROJECT\DATASET\img367 right-bot 28188787,-14,-F.png
367
E:\COM\PROJECT\DATASET\img368 right-bot 33918447,-14,-F.png
368
E:\COM\PROJECT\DATASET\img369 right-bot 37272978,-14,-F.png
369
E:\COM\PROJECT\DATASET\img370 right-bot 38268204,-14,-F.png
370
E:\COM\PROJECT\DATASET\img371 right-top 08089699,-14,-F.png
371
E:\COM\PROJECT\DATASET\img372 right-top 12966537,-14,-F.png
372
E:\COM\PROJECT\DATASET\img373 right-top 26343359,-14,-F.png
373
E:\COM\PROJECT\DATASET\img374 right-top 26475250,-14,-F.png
374
E:\COM\PROJECT\DATASET\img375 right-t

486
E:\COM\PROJECT\DATASET\img487 right-top 22581612,-18,-F.png
487
E:\COM\PROJECT\DATASET\img488 right-top 26208458,-18,-F.png
488
E:\COM\PROJECT\DATASET\img489 right-top 26480357,-18,-F.png
489
E:\COM\PROJECT\DATASET\img490 right-top 26495089,-18,-F.png
490
E:\COM\PROJECT\DATASET\img491 right-top 38290410,-18,-F.png
491
E:\COM\PROJECT\DATASET\img492 right-top 38947750,-18,-F.png
492
E:\COM\PROJECT\DATASET\img493 right-top 39258211,-18,-F.png
493
E:\COM\PROJECT\DATASET\img494 right-top 39603035,-18,-F.png
494
E:\COM\PROJECT\DATASET\img495 rihg-bot 10720089,-18,-F.png
495
E:\COM\PROJECT\DATASET\img496 rihg-bot 16842152,-18,-F.png
496
E:\COM\PROJECT\DATASET\img497 rihg-bot 22581612,-18,-F.png
497
E:\COM\PROJECT\DATASET\img498 rihg-bot 26208458,-18,-F.png
498
E:\COM\PROJECT\DATASET\img499 rihg-bot 26480357,-18,-F.png
499
E:\COM\PROJECT\DATASET\img500 rihg-bot 26495089,-18,-F.png
500
E:\COM\PROJECT\DATASET\img501 rihg-bot 38290410,-18,-F.png
501
E:\COM\PROJECT\DATASET\img502 rihg-bot 3894

E:\COM\PROJECT\DATASET\img613 left-bot 14716231,-6,-M.png
613
E:\COM\PROJECT\DATASET\img614 left-bot 15218330,-6,-M.png
614
E:\COM\PROJECT\DATASET\img615 left-bot 21576590,-6,-M.png
615
E:\COM\PROJECT\DATASET\img616 left-bot 21838850,-6,-M.png
616
E:\COM\PROJECT\DATASET\img617 left-bot 23038953,-6,-M.png
617
E:\COM\PROJECT\DATASET\img618 left-top 14716231,-6,-M.png
618
E:\COM\PROJECT\DATASET\img619 left-top 15218330,-6,-M.png
619
E:\COM\PROJECT\DATASET\img620 left-top 21576590,-6,-M.png
620
E:\COM\PROJECT\DATASET\img621 left-top 21838850,-6,-M.png
621
E:\COM\PROJECT\DATASET\img622 left-top 23038953,-6,-M.png
622
E:\COM\PROJECT\DATASET\img623 right-bot 14716231,-6,-M.png
623
E:\COM\PROJECT\DATASET\img624 right-bot 15218330,-6,-M.png
624
E:\COM\PROJECT\DATASET\img625 right-bot 21576590,-6,-M.png
625
E:\COM\PROJECT\DATASET\img626 right-bot 21838850,-6,-M.png
626
E:\COM\PROJECT\DATASET\img627 right-bot 23038953,-6,-M.png
627
E:\COM\PROJECT\DATASET\img628 right-top 14716231,-6,-M.png
628
E:

742
E:\COM\PROJECT\DATASET\img743 right-top 08572623,-9,-M.png
743
E:\COM\PROJECT\DATASET\img744 right-top 08826063,-9,-M.png
744
E:\COM\PROJECT\DATASET\img745 right-top 20909708,-9,-M.png
745
E:\COM\PROJECT\DATASET\img746 right-top 21477428,-9,-M.png
746
E:\COM\PROJECT\DATASET\img747 right-top 21964508,-9,-M.png
747
E:\COM\PROJECT\DATASET\img748 right-top 22104477,-9,-M.png
748
E:\COM\PROJECT\DATASET\img749 right-top 22266900,-9,-M.png
749
E:\COM\PROJECT\DATASET\img750 right-top 22715239,-9,-M.png
750
E:\COM\PROJECT\DATASET\img751 right-top 27161729,-9,-M.png
751
E:\COM\PROJECT\DATASET\img752 right-top 31224395,-9,-M.png
752
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
E:\COM\PROJECT\DATASET\img753 left-bot 04383241,-10,-M.png
753
E:\COM\PROJECT\DATASET\img754 left-bot 08055210,-10,-M.png
754
E:\COM\PROJECT\DATASET\img755 left-bot 08159789,-10,-M.png
755
E:\COM\PROJECT\DATASET\img756 left-bot 08570768,-10,-M.png
756
E:\COM\PROJECT\DATASET\img757 left-bot 09379016,-10

871
E:\COM\PROJECT\DATASET\img872 right-top 26326558,-13,-M.png
872
E:\COM\PROJECT\DATASET\img873 right-top 27635480,-13,-M.png
873
E:\COM\PROJECT\DATASET\img874 right-top 39187254,-13,-M.png
874
E:\COM\PROJECT\DATASET\img875 right-top 39312449,-13,-M.png
875
E:\COM\PROJECT\DATASET\img876 right-top 40130274,-13,-M.png
876
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
E:\COM\PROJECT\DATASET\img877 left-bot 01679112,-14,-M.png
877
E:\COM\PROJECT\DATASET\img878 left-bot 10785882,-14,-M.png
878
E:\COM\PROJECT\DATASET\img879 left-bot 13158834,-14,-M.png
879
E:\COM\PROJECT\DATASET\img880 left-bot 13373477,-14,-M.png
880
E:\COM\PROJECT\DATASET\img881 left-bot 13571581,-14,-M.png
881
E:\COM\PROJECT\DATASET\img882 left-bot 21473493,-14,-M.png
882
E:\COM\PROJECT\DATASET\img883 left-bot 25179814,-14,-M.png
883
E:\COM\PROJECT\DATASET\img884 left-bot 25763932,-14,-M.png
884
E:\COM\PROJECT\DATASET\img885 left-bot 29086536,-14,-M.png
885
E:\COM\PROJECT\DATASET\img886 left-bot 

998
E:\COM\PROJECT\DATASET\img999 right-bot 26104411,-17,-M.png
999
E:\COM\PROJECT\DATASET\img1000 right-bot 26107935,-17,-M.png
1000
E:\COM\PROJECT\DATASET\img1001 right-bot 26238923,-17,-M.png
1001
E:\COM\PROJECT\DATASET\img1002 right-bot 39419973,-17,-M.png
1002
E:\COM\PROJECT\DATASET\img1003 right-top 07642882,-17,-M.png
1003
E:\COM\PROJECT\DATASET\img1004 right-top 15114049,-17,-M.png
1004
E:\COM\PROJECT\DATASET\img1005 right-top 23031262,-17,-M.png
1005
E:\COM\PROJECT\DATASET\img1006 right-top 24428083,-17,-M.png
1006
E:\COM\PROJECT\DATASET\img1007 right-top 25387066,-17,-M.png
1007
E:\COM\PROJECT\DATASET\img1008 right-top 25842743,-17,-M.png
1008
E:\COM\PROJECT\DATASET\img1009 right-top 26104411,-17,-M.png
1009
E:\COM\PROJECT\DATASET\img1010 right-top 26107935,-17,-M.png
1010
E:\COM\PROJECT\DATASET\img1011 right-top 26238923,-17,-M.png
1011
E:\COM\PROJECT\DATASET\img1012 right-top 39419973,-17,-M.png
1012
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
ignore
E:\C

In [4]:
print(os.chdir("E:/COM/PROJECT"))
df=pd.read_csv("result.csv")
print(df.filename)

None
0      img1001 right-bot 26238923,-17,-M.jpg
1      img1003 right-top 07642882,-17,-M.jpg
2      img1004 right-top 15114049,-17,-M.jpg
3      img1005 right-top 23031262,-17,-M.jpg
4      img1006 right-top 24428083,-17,-M.jpg
                       ...                  
994      img977 left-bot 25387066,-17,-M.jpg
995      img980 left-bot 26107935,-17,-M.jpg
996      img983 left-top 07642882,-17,-M.jpg
997      img987 left-top 25387066,-17,-M.jpg
998      img992 left-top 39419973,-17,-M.jpg
Name: filename, Length: 999, dtype: object


In [5]:
os.chdir('DATASET')
x=list(df.filename)


In [6]:
print(os.getcwd())
counth=[]
countw=[]
count=0
for(dirname, dirs, files) in os.walk('.'):
    for filename in files:
        if filename in x:
            image = cv2.imread(filename)
            print('true')
            counth.append(image.shape[0])
            countw.append(image.shape[1])
            count=count+1
            im=cv2.resize(image,(700,550))
            cv2.imwrite(filename,im)
            
        else:
            image=cv2.imread(filename)
            im=cv2.resize(image,(10,10))
            cv2.imwrite(filename,im)

E:\COM\PROJECT\DATASET
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
tr

In [7]:
print(count)
np.histogram(countw)


999


(array([  0,   0,   0,   0,   0, 999,   0,   0,   0,   0], dtype=int32),
 array([549.5, 549.6, 549.7, 549.8, 549.9, 550. , 550.1, 550.2, 550.3,
        550.4, 550.5]))

In [8]:
np.histogram(counth)

(array([  0,   0,   0,   0,   0, 999,   0,   0,   0,   0], dtype=int32),
 array([699.5, 699.6, 699.7, 699.8, 699.9, 700. , 700.1, 700.2, 700.3,
        700.4, 700.5]))